name: CI test
on: push
jobs:
  Heoll:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        id: wew
        run: |
          echo "greeting=hello" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
          
