name: CI
on: 
  push:
    branches: Sharath246-patch-2
jobs:
  Heoll:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - run: | 
          cd /usr/local/bin/python code &&
          find . -print
  abcdef:
    needs: Heoll
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "Hello World"
      - name: hello sharath
        if: always()
        run: echo "Hello Sharath"
