name: CI test
on: push
jobs:
  Heoll:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        id: wew
        run: |
          echo "greeting=hello" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT >> abc.txt
          cat abc.txt
          echo $GITHUB_OUTPUT
          
