name: CI test
on: 
  push:
    branches:
      - abcd
jobs:
  Heoll:
    outputs:
      greetings: ${{steps.wew.outputs.greeting}}
    runs-on: ubuntu-latest
    steps:
      - name: hello
        id: wew
        run: echo "greeting=hello" >> $GITHUB_OUTPUT
  Hello:
    runs-on: ubuntu-latest
    needs: Heoll
    steps:
      - run: echo "${{needs.Heoll.outputs.greetings}}"
