name: CI
on: 
  push:
    branches:
      - main
jobs:
  Heoll:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          repository: Sharath246/cicd
          token: ${{secrets.CICDTOKEN}}
          event-type: abcd
