name: CI test
on: push
jobs:
  Heoll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "$GITHUB_WORKSPACE"
      - run: echo "$WORKSPACE"
      - name: hello
        id: wew
        run: |
          echo "greeting=hello" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
          
